// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1rCFrcGSLVvDEB0edixWJEM_y_dNWHQ',
    appId: '1:314057536258:web:b8960852eae41bede7881b',
    messagingSenderId: '314057536258',
    projectId: 'animeverse-c0600',
    authDomain: 'animeverse-c0600.firebaseapp.com',
    storageBucket: 'animeverse-c0600.appspot.com',
    measurementId: 'G-XXJDB7KH26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRz4zjHUjtusstFRXcQvRw2jTvYzACjo',
    appId: '1:314057536258:android:c1e1828b65474699e7881b',
    messagingSenderId: '314057536258',
    projectId: 'animeverse-c0600',
    storageBucket: 'animeverse-c0600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYHDOYsFxXhhIiqJVIu8JCNTbgx0Qjp4',
    appId: '1:314057536258:ios:a0b2031d39e65cf1e7881b',
    messagingSenderId: '314057536258',
    projectId: 'animeverse-c0600',
    storageBucket: 'animeverse-c0600.appspot.com',
    iosBundleId: 'com.example.aniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYHDOYsFxXhhIiqJVIu8JCNTbgx0Qjp4',
    appId: '1:314057536258:ios:a0b2031d39e65cf1e7881b',
    messagingSenderId: '314057536258',
    projectId: 'animeverse-c0600',
    storageBucket: 'animeverse-c0600.appspot.com',
    iosBundleId: 'com.example.aniverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo1rCFrcGSLVvDEB0edixWJEM_y_dNWHQ',
    appId: '1:314057536258:web:3793b5f52ca2197be7881b',
    messagingSenderId: '314057536258',
    projectId: 'animeverse-c0600',
    authDomain: 'animeverse-c0600.firebaseapp.com',
    storageBucket: 'animeverse-c0600.appspot.com',
    measurementId: 'G-W2TT09K6RF',
  );
}
